# Generated by Django 4.1 on 2023-10-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_departamento_anulate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shor_name')},
        ),
    ]
